var AllTeams = [
			{"name": "Arsenal", "logo": "./Images/Arsenal.jpg", "Nickname": "The Gunners", "Founded": 1886, "Stadium": "Emirates Stadium", "Capacity": 60432,
			"Manager": "Arsene Wenger", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=85"},
			{"name": "Bournemouth", "logo": "./Images/Bournemouth.png", "Nickname": "N/A", "Founded": 1899, "Stadium": "Dean Court", "Capacity": 11464,
			"Manager": "Eddie Howe", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=14886"},
			{"name": "Burnley", "logo": "./Images/Burnley.png", "Nickname": "The Clarets", "Founded": 1882, "Stadium": "Turf Moor", "Capacity": 21401,
			"Manager": "Sean Dyche", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=1488"},
			{"name": "Chelsea", "logo": "./Images/Chelsea.png", "Nickname": "The Blues", "Founded": 1905, "Stadium": "Stamford Bridge", "Capacity": 41631,
			"Manager": "Antonio Conte", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=103"},
			{"name": "Crystal Palace", "logo": "./Images/CrystalPalace.jpg", "Nickname": "Eagles", "Founded": 1905, "Stadium": "Selhurst Park", "Capacity": 25456,
			"Manager": "Alan Pardew", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=8"},
			{"name": "Everton", "logo": "./Images/Everton.jpg", "Nickname": "The Tofees", "Founded": 1878, "Stadium": "Goodison Park", "Capacity": 39572,
			"Manager": "Ronald Koeman", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=111"},
			{"name": "Hull City", "logo": "./Images/Hull.png", "Nickname": "The Tigers", "Founded": 1904, "Stadium": "KCOM Stadium", "Capacity": 25450,
			"Manager": "Mike Phelan", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=14883"},
			{"name": "Leicester City", "logo": "./Images/Leicester.jpg", "Nickname": "The Foxes", "Founded": 1884, "Stadium": "King Power Stadium", "Capacity": 32312,
			"Manager": "Claudio Ranieri", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=21"},
			{"name": "Liverpool", "logo": "./Images/Liverpool.png", "Nickname": "The Reds", "Founded": 1892, "Stadium": "Anfield", "Capacity": 54074,
			"Manager": "Jurgen Klopp", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=129"},
			{"name": "Man City", "logo": "./Images/ManCity.png", "Nickname": "The Citizens", "Founded": 1880, "Stadium": "Ethihad Stadium", "Capacity": 60000,
			"Manager": "Pep Guardiola", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=131"},
			{"name": "Man United", "logo": "./Images/ManUnited.png", "Nickname": "The Red Devils", "Founded": 1878, "Stadium": "Old Trafford", "Capacity": 75635,
			"Manager": "Jose Mourinho", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=132"},
			{"name": "Middlesbrough", "logo": "./Images/Middlesbrough.jpg", "Nickname": "The Boro", "Founded": 1876, "Stadium": "Riverside Stadium", "Capacity": 34732,
			"Manager": "Aitor Karanka", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=428"},
			{"name": "Southampton", "logo": "./Images/Southampton.png", "Nickname": "The Saints", "Founded": 1885, "Stadium": "St. Mary's Stadium", "Capacity": 32505,
			"Manager": "Claude Puel", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=1516"},
			{"name": "Stoke City", "logo": "./Images/StokeCity.jpg", "Nickname": "The Potters", "Founded": 1863, "Stadium": "Bet365 Stadium", "Capacity": 27902,
			"Manager": "Steve Bruce", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=461"},
			{"name": "Sunderland", "logo": "./Images/Sunderland.jpg", "Nickname": "The Black Cats", "Founded": 1879, "Stadium": "Stadium of Light", "Capacity": 49000,
			"Manager": "David Moyes", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=462"},
			{"name": "Swansea City", "logo": "./Images/SwanseaCity.png", "Nickname": "The Swans", "Founded": 1912, "Stadium": "Liberty Stadium", "Capacity": 21088,
			"Manager": "Bob Bradey", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=67"},
			{"name": "Tottenham", "logo": "./Images/Tottenham.jpg", "Nickname": "Spurs", "Founded": 1882, "Stadium": "White Hart Lane", "Capacity": 36284,
			"Manager": "Mauricio Pochettino", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=68"},
			{"name": "Watford", "logo": "./Images/Watford.png", "Nickname": "The Hornets", "Founded": 1881, "Stadium": "Vicarage Road", "Capacity": 21438,
			"Manager": "Gino Pozzo", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=14887"},
			{"name": "West Brom", "logo": "./Images/WestBrom.png", "Nickname": "The Baggies", "Founded": 1878, "Stadium": "The Hawthorns", "Capacity": 26850,
			"Manager": "Tony Pulis", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=76"},
			{"name": "West Ham", "logo": "./Images/WestHam.png", "Nickname": "The Hammers", "Founded": 1895, "Stadium": "London Stadium", "Capacity": 60000,
			"Manager": "Slaven Bilic", "latestNews": "http://cdn.footballfancast.com/widgets/latest-news/widget-mpu.html?cat=77"}			
];



export default AllTeams;